apiVersion: v1
kind: Service
metadata:
  labels:
    app: learncontainers
  name: learncontainers
spec:
  ports:
    - nodePort: 30000
      targetPort: 5000
      port: 5000
  selector:
    app: learncontainers
  type: NodePort
